### ISSUE TITLE
Login to ALBS using AL SSO is broken

### ISSUE THREAD

**Issue by soksanichenko** [AlmaLinux/build-system#322]
Keycloak returns `Client not found`

![Image](https://github.com/user-attachments/assets/c36fc5a9-74bc-4be8-aad8-c08de18dea9f)

**Comment by jonathanspw** [comment]
@javihernandez @soksanichenko it was never made it work.  I need to coordinate with someone on putting production keys in place for keycloak.  Who should that be?

**Comment by javihernandez** [comment]
> @javihernandez @soksanichenko it was never made to work. I need to coordinate with someone on putting production keys in place for keycloak. Who should that be?

@Korulag ?

**Comment by Korulag** [comment]
@jonathanspw what should I do to make it work?

**Comment by jonathanspw** [comment]
> @jonathanspw what should I do to make it work?

I'll message you on MM.

**Comment by javihernandez** [comment]
It's fixed now - @jonathanspw and I triaged that and the main problem was that the token we were getting was longer than what can be allocated in db. We removed roles from the token coming from KeyCloak as we're not using them right now, but created https://github.com/AlmaLinux/build-system/issues/329, because we'd need to increase the column size at some point.
